### ISSUE TITLE
Create User management solution(microservice) 

### ISSUE THREAD

**Issue by hyunbin7303** [HappYness-Project/Happy-EventSourcing#37]
# Implementation Plan
- [x] Define the data models for the user, role, claims etc.
- [x] Build the solution
- [x] Create projects for Identity.Domain, Infrastructure,Application and Web.
- [x] Connect to the PostgreSQL.
- [x] Create DB Tables.
