### ISSUE TITLE
Todo Details | TodoItem moves to the Completed Section when it is Completed. 

### ISSUE THREAD

**Issue by hyunbin7303** [HappYness-Project/Happy-EventSourcing#55]
- [x] Create "Completed" Section.
- [x] Todo Item moves to "Completed" section when the user clicks "Done" in the status. 
- [x] Update API for retrieving "Completed" Task.
